'''Q1'''
a = int(input('Enter a: '))
b = int(input('Enter b: '))
print('Add: ',a+b)
print('Sub: ',a-b)
print('Mul: ',a*b)
print('Div: ',a/b)
print('Div: ',a//b)
print('Reminder: ',a%b)
print('Power: ',a**b)