list = ['Vandan','Sanat','Amar','Nitesh','Prasanth']
list.append('Gopal')
print(list)
list1 = list.copy()
print(list1)
print(list.count('Sanat'))
list2 = ['vijay','Sankar']
print(list.extend(list2))
print(list.index('Nitesh'))
list.insert(2,"Jay")
print(list)
print(list.pop(4))
list.reverse()
print(list)
list.sort()
print(list)
list.clear()
print(list)